-- V030: recurring monthly subscriptions, welfare disbursement security and
-- staff resign/expelled support.
--
-- SUBSCRIPTIONS become a RECURRING model: exactly ONE row per family acts as
-- the family's subscription account, recorded against the family HEAD. Each
-- month the SAME row is rolled over to the new period (amount = configured
-- monthly rate, e.g. 200; amount_paid resets) — no new row per month. The
-- actual money movements live in the new append-only subscription_payments
-- table (one payment record per family per month), which is also what the
-- accounting ledger / dashboard read, so history survives the monthly reset.
--
-- WELFARE gains minutes_date: the date of the committee minutes in which the
-- assistance amount was agreed — recorded at approval, verified at
-- disbursement (disbursing also requires a reason + administrator password).
--
-- STAFF gains the 'Expelled' status (next to Active/Inactive/Resigned) so a
-- resignation and an expulsion can be told apart in the register and reports.

-- ===== 1. Immutable payment ledger for subscriptions =====
CREATE TABLE IF NOT EXISTS subscription_payments (
    id              INTEGER PRIMARY KEY AUTOINCREMENT,
    subscription_id INTEGER NOT NULL,
    family_id       INTEGER NOT NULL,
    member_id       INTEGER,
    period_start    TEXT,
    period_end      TEXT,
    amount          REAL NOT NULL DEFAULT 0,          -- how much was actually given this month
    receipt_number  TEXT,
    payment_date    TEXT,
    payment_method  TEXT DEFAULT 'Cash',
    transaction_ref TEXT DEFAULT '',
    collected_by    INTEGER,
    remarks         TEXT DEFAULT '',
    status          TEXT NOT NULL DEFAULT 'Active' CHECK (status IN ('Active','Cancelled')),
    created_at      TEXT NOT NULL DEFAULT (datetime('now')),
    updated_at      TEXT NOT NULL DEFAULT (datetime('now')),
    FOREIGN KEY (subscription_id) REFERENCES subscriptions(id) ON DELETE CASCADE,
    FOREIGN KEY (family_id) REFERENCES families(id) ON DELETE RESTRICT,
    FOREIGN KEY (member_id) REFERENCES members(id) ON DELETE SET NULL,
    FOREIGN KEY (collected_by) REFERENCES users(id) ON DELETE SET NULL
);
CREATE INDEX IF NOT EXISTS idx_subpay_family ON subscription_payments(family_id);
CREATE INDEX IF NOT EXISTS idx_subpay_period ON subscription_payments(period_start);
CREATE INDEX IF NOT EXISTS idx_subpay_receipt ON subscription_payments(receipt_number);
CREATE INDEX IF NOT EXISTS idx_subpay_status ON subscription_payments(status);

-- ===== 2. Backfill: every already-paid subscription month becomes a payment
-- record so no financial history is lost by the consolidation below. =====
INSERT INTO subscription_payments
    (subscription_id, family_id, member_id, period_start, period_end, amount,
     receipt_number, payment_date, payment_method, transaction_ref, collected_by, remarks, status)
SELECT s.id, s.family_id, s.member_id, s.period_start, s.period_end, s.amount_paid,
       s.receipt_number, COALESCE(s.payment_date, s.period_start), COALESCE(s.payment_method, 'Cash'),
       COALESCE(s.transaction_ref, ''), s.collected_by, s.remarks, 'Active'
FROM subscriptions s
WHERE COALESCE(s.amount_paid, 0) > 0;

-- ===== 3. Consolidate to ONE subscription row per family =====
-- Keep the most recent row per family (latest period); older rows are
-- superseded (their payments were copied above). Before deleting the
-- superseded rows, repoint every payment record to the family's KEPT row so
-- the ON DELETE CASCADE of step 1 cannot destroy the history we just saved.
UPDATE subscription_payments
SET subscription_id = (
  SELECT s2.id FROM subscriptions s2
  WHERE s2.family_id = subscription_payments.family_id
  ORDER BY COALESCE(s2.period_start, '') DESC, s2.id DESC
  LIMIT 1
);

DELETE FROM subscriptions
WHERE id NOT IN (
  SELECT id FROM (
    SELECT id, ROW_NUMBER() OVER (
      PARTITION BY family_id
      ORDER BY COALESCE(period_start, '') DESC, id DESC
    ) AS rn
    FROM subscriptions
  ) WHERE rn = 1
);

-- The kept row is re-pointed at the current head so the subscription is
-- always "recorded in the head of person".
UPDATE subscriptions
SET member_id = COALESCE(
  (SELECT m.id FROM members m
    WHERE m.family_id = subscriptions.family_id AND m.archive_state = 0
    ORDER BY CASE WHEN m.is_head = 1 THEN 0 WHEN m.relationship = 'Head' THEN 1 ELSE 2 END, m.id
    LIMIT 1),
  member_id
);

-- Receipts now live on the monthly payment records; the subscription row
-- mirrors only the CURRENT month's receipt (set by the app each month).
-- Clearing it here also frees the UNIQUE constraint from collisions with
-- receipts generated by the new sequence.
UPDATE subscriptions SET receipt_number = NULL;

-- ===== 4. Welfare: date of the committee minutes that approved the amount =====
ALTER TABLE welfare_requests ADD COLUMN minutes_date TEXT;

-- ===== 5. Staff: allow the 'Expelled' status =====
-- SQLite cannot ALTER a CHECK constraint, so rebuild the table. Child table
-- staff_payments references staff(id), so both are rebuilt together
-- (foreign_keys=ON on this connection makes dropping the parent alone fail).
CREATE TABLE IF NOT EXISTS staff_v030 (
  id                  INTEGER PRIMARY KEY AUTOINCREMENT,
  staff_code          TEXT NOT NULL UNIQUE,
  member_id           INTEGER,
  name                TEXT NOT NULL,
  role                TEXT NOT NULL DEFAULT 'Staff',
  phone               TEXT DEFAULT '',
  email               TEXT DEFAULT '',
  address             TEXT DEFAULT '',
  joined_date         TEXT,
  salary              REAL NOT NULL DEFAULT 0,
  payment_frequency   TEXT NOT NULL DEFAULT 'Monthly' CHECK (payment_frequency IN ('Monthly','Quarterly','Annually','OnDemand')),
  status              TEXT NOT NULL DEFAULT 'Active' CHECK (status IN ('Active','Inactive','Resigned','Expelled')),
  notes               TEXT DEFAULT '',
  archive_state       INTEGER NOT NULL DEFAULT 0,
  archive_source      TEXT,
  archived_at         TEXT,
  archived_by         INTEGER,
  archive_reason      TEXT,
  created_at          TEXT NOT NULL DEFAULT (datetime('now')),
  updated_at          TEXT
);

CREATE TABLE IF NOT EXISTS staff_payments_v030 (
  id                INTEGER PRIMARY KEY AUTOINCREMENT,
  staff_id          INTEGER NOT NULL,
  period_month      INTEGER NOT NULL CHECK (period_month BETWEEN 1 AND 12),
  period_year       INTEGER NOT NULL,
  amount            REAL NOT NULL DEFAULT 0,
  payment_date      TEXT NOT NULL DEFAULT (date('now')),
  payment_method    TEXT DEFAULT 'Cash',
  transaction_ref   TEXT DEFAULT '',
  status            TEXT NOT NULL DEFAULT 'Paid' CHECK (status IN ('Paid','Pending','Cancelled')),
  notes             TEXT DEFAULT '',
  paid_by           INTEGER,
  created_at        TEXT NOT NULL DEFAULT (datetime('now'))
);

INSERT INTO staff_v030 SELECT * FROM staff;
INSERT INTO staff_payments_v030 SELECT * FROM staff_payments;
DROP TABLE staff_payments;
DROP TABLE staff;
ALTER TABLE staff_v030 RENAME TO staff;
ALTER TABLE staff_payments_v030 RENAME TO staff_payments;

CREATE UNIQUE INDEX IF NOT EXISTS idx_staff_code ON staff(staff_code);
CREATE INDEX IF NOT EXISTS idx_staff_status ON staff(status, archive_state);
CREATE INDEX IF NOT EXISTS idx_staff_role ON staff(role);
CREATE INDEX IF NOT EXISTS idx_staff_payments_staff ON staff_payments(staff_id, period_year, period_month);
CREATE INDEX IF NOT EXISTS idx_staff_payments_period ON staff_payments(period_year, period_month);

-- Audit trigger dropped with the old table — recreate it.
CREATE TRIGGER IF NOT EXISTS trg_staff_updated AFTER UPDATE ON staff BEGIN
  UPDATE staff SET updated_at = datetime('now') WHERE id = NEW.id;
END;
